sudo: false
language: node_js
branches:
  only:
    - master
    - /^greenkeeper/.*$/
notifications:
  email: false
node_js:
  - "10"
  - "9"
  - "8"
  - "7"
  - "6"
install:
  - 'npm install -g npm@6'
script:
  - 'npm test'
matrix:
  fast_finish: true

